openapi: 3.0.0

info:
  title: Chocs API with chinook DB
  description: Showcase app of chocs, kink and gata libraries
  version: 0.2.0

paths:
  /artists:
    get:
      summary: List artists
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    items:
                      $ref: "#/components/schemas/Artist"
                  paging:
                    $ref: '#/components/schemas/Paginator'
                  _links:
                    $ref: '#/components/schemas/PaginatorLinks'
    parameters:
      - name: $limit
        in: query
        description: Limit mount of records
        required: false
        schema:
          type: integer
          default: 10
      - name: $offset
        in: query
        description: Sets offset for resultset
        required: false
        schema:
          type: integer
          default: 0
      - name: $sort
        in: query
        description: Comma separated fields, used to sort resultset.
        required: false
        schema:
          type: string
  /albums:
    get:
      summary: List artists
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    items:
                      $ref: "#/components/schemas/Album"
                  paging:
                    $ref: '#/components/schemas/Paginator'
                  _links:
                    $ref: '#/components/schemas/PaginatorLinks'
    parameters:
      - name: $limit
        in: query
        description: Limit mount of records
        required: false
        schema:
          type: integer
          default: 10
      - name: $offset
        in: query
        description: Sets offset for resultset
        required: false
        schema:
          type: integer
          default: 0
      - name: $sort
        in: query
        description: Comma separated fields, used to sort resultset.
        required: false
        schema:
          type: string
components:
  schemas:
    Artist:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Album:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        artist:
          $ref: "#/components/schemas/Artist"
    Paginator:
      type: object
      properties:
        offset:
          type: integer
          default: 0
        limit:
          type: integer
          default: 10
        total_items:
          type: integer
    PaginatorLinks:
      type: array
      items:
        $ref: '#/components/schemas/PaginatorHateos'

    PaginatorHateos:
      type: object
      properties:
        rel:
          type: string
          description: location type
          enum:
            - "self"
            - "previous"
            - "next"
        href:
          type: string
          description: url address to the location
          example: "/resource"
        method:
          type: string
          enum:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"


